version: '3.8'

services:
  whatsapp-connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-n8n-connector
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - NODE_ENV=production
      - LOG_LEVEL=info
      - API_KEY=${API_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=*
      - RESTART_ON_CRASH=true
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  whatsapp-network:
    driver: bridge
